# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: guess_who_no_fuzzy 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "guess_who_no_fuzzy"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["odina", "roy"]
  s.date = "2017-10-19"
  s.description = "Extracts name from username or email"
  s.email = ["odina.abellana@gmail.com", "roy.evan.sia@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "files/females.txt",
    "files/initials.txt",
    "files/males.txt",
    "files/surnames.txt",
    "guess_who_no_fuzzy.gemspec",
    "lib/guess_who_no_fuzzy.rb",
    "lib/guess_who_no_fuzzy/comparator.rb",
    "lib/guess_who_no_fuzzy/names_loader.rb",
    "lib/guess_who_no_fuzzy/profiler.rb",
    "lib/guess_who_no_fuzzy/scorer.rb",
    "lib/guess_who_no_fuzzy/tokenizer.rb",
    "spec/lib/profiler_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/darklight721/guess_who"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Extract name from email"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.15"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.2.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.15"])
      s.add_dependency(%q<jeweler>, ["~> 2.2.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.15"])
    s.add_dependency(%q<jeweler>, ["~> 2.2.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

